export const SEARCH_IS_LOADING = 'SEARCH_IS_LOADING';
export const SEARCH_IS_LOADED = 'SEARCH_IS_LOADED';

export const MOVIE_MODAL_OPEN = 'MOVIE_MODAL_OPEN';
export const MOVIE_MODAL_CLOSE = 'MOVIE_MODAL_CLOSE';
export const MOVIE_MODAL_IS_LOADED = 'MOVIE_MODAL_IS_LOADED';

export const SERIES_MODAL_OPEN = 'SERIES_MODAL_OPEN';
export const SERIES_MODAL_CLOSE = 'SERIES_MODAL_CLOSE';
export const SERIES_MODAL_IS_LOADED = 'SERIES_MODAL_IS_LOADED';

export const MOVIE_IS_SAVING = 'MOVIE_IS_SAVING';
export const MOVIE_IS_SAVED = 'MOVIE_IS_SAVED';